controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    hand_controller:
      type: joint_trajectory_controller/JointTrajectoryController

hand_controller:
  ros__parameters:
    joints:
      - left_finger_joint
      - right_finger_joint
    command_interfaces:
      - position
      - effort
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: false
